# 24 CSV 파일 다루기
## 1. CSV 파일의 이해
### (1) CSV 파일 살펴보기
### (2) CSV 파일 생성하기
- 엑셀에서 사용하는 표 형식을 텍스트 형태로 변환한 파일
  - 데이터 구조를 표현하는 가장 간결한 형태의 파일로서, 엑셀의 행은 한 줄로 표현하고 엑셀의 열은 콤마(,)로 구분하는 형식이다 (txt로 열면 알 수 있음)



## 2. CSV 파일 저장하기
### (1) 딕셔너리를 포함하는 리스트 구조를 CSV로 저장하기
- 초기화
  - csv 파일의 한 행에 대한 구문 형식 정의
- csv 파일 저장을 위한 f객체 생성
  - Excel의 csv는 euc-kr 형식
- 첫 줄에 각 항목의 제목 기록
- 각 데이터를 한 줄씩 콤마로 구분하여 기록
### (2) 다른 형식의 데이터를 CSV로 저장하기
  - 한 행의 템플릿 (초기화)
  - 딕셔너리의 키를 리스트로 변환
  - keys 리스트 사이에 쉼표를 넣어 문자열로 변환
  - 첫 줄에 각 행목 제목 기록
  - 각 데이터를 한 줄씩 콤마로 구분하여 기록

In [2]:
# (1) 딕셔너리를 포함하는 리스트 구조를 CSV로 저장하기
grade = [
    {"name": "철수", 'kor':95, 'eng':88, 'math':72},
    {"name": "영희", 'kor':92, 'eng':98, 'math':95},
    {"name": "철민", 'kor':88, 'eng':76, 'math':64}
]

tpl= "{0},{1},{2},{3}\n"

with open("grade.csv","w", encoding = 'euc-kr') as f:
    f.write("이름, 국어, 영어, 수학\n")

    for item in grade:
        tmp = tpl.format(item["name"], item["kor"], item["eng"], item["math"])
        f.write(tmp)

In [4]:
# (2) 다른 형식의 데이터를 CSV로 저장하기
grade_dic= {
    '이름': ['철수', '영희', '민철', '수현', '호영'],
    '국어': [98, 88, 92, 63, 120],
    '영어': [76, 90, 70, 60, 50],
    '수학': [88, 62, 88, 31, 76],
    '과학': [64, 72, 45, 70, 88]
}

tpl = "{0},{1},{2},{3},{4}\n"
keys = list(grade_dic.keys())
p = ","
title = p.join(keys)

with open("grade2.csv", "w", encoding = 'euc-kr') as f:
    f.write(title+"\n")

    for i in range(0, len(grade_dic['이름'])):
        tmp = tpl.format(grade_dic['이름'][i], grade_dic['국어'][i], grade_dic['영어'][i],
                         grade_dic['수학'][i], grade_dic['과학'][i])
        f.write(tmp)

## 3. CSV 파일 읽어오기

### (1) CSV파일의 내용을 파이썬 데이터로 변환 (Step-1)
- 읽어들인 내용을 저장하기 위한 빈 변수 생성
- grade.csv 파일에 대한 파일 객체를 읽기 모드로 생성
  - 파일의 각 행을 원소로 갖는 리스트 생성
  
### (2) CSV파일의 내용을 파이썬 데이터로 변환 (Step-2)
- CSV의 데이터를 저장할 빈 배열
- 첫 행은 제목이므로 건너뜀
- 현재 행의 내용을 콤마를 기준으로 잘라 리스트로 변환
  - split()의 결과로 생성된 리스트의 모든 원소는 string타입 (""가 삽입됨)
- 한 행의 내용을 딕셔너리로 변환
- 딕셔너리를 미리 준비한 리스트에 추가

In [7]:
# (1) CSV파일의 내용을 파이썬 데이터로 변환 (Step-1)

csv_list = None

with open("grade.csv", "r", encoding='euc-kr') as f:
    csv_list = f.readlines()

print(csv_list)

# (2) CSV파일의 내용을 파이썬 데이터로 변환 (Step-2)
data = []
for i, line in enumerate(csv_list):
    if i == 0:
        continue # 제목은 저장 안할 것
    
    k = line.strip().split(",")
    
    item = {"name":k[0], "kor": int(k[1]), "eng": int(k[2]), "math":(int(k[3]))}

    data.append(item)

data

['이름, 국어, 영어, 수학\n', '철수,95,88,72\n', '영희,92,98,95\n', '철민,88,76,64\n']

[{'name': '철수', 'kor': 95, 'eng': 88, 'math': 72},
 {'name': '영희', 'kor': 92, 'eng': 98, 'math': 95},
 {'name': '철민', 'kor': 88, 'eng': 76, 'math': 64}]

In [88]:
## 연구과제. CSV파일로부터 인사이트 찾기

csv_traffic = None

with open("traffic_acc.csv", "r", encoding="utf-8") as f:
    csv_traffic = f.readlines()

    print(csv_traffic)

data = []

for i, line in enumerate(csv_traffic):
    if i == 0:
        continue
    k = line.strip().split(",")
    item = {"연도":int(k[0]), "월":int(k[1]), "발생건수":int(k[2]), "사망자수":int(k[3]), "부상자수":int(k[4])}

    data.append(item)
data


# 1) 해당 기간 동안 발생한 전체 교통사고의 발생건수, 사망자 수, 부상자 수
acc = 0
death = 0
inj = 0
for i in range(0, len(data)):
    acc += data[i]['발생건수']
    death += data[i]['사망자수']
    inj += data[i]['부상자수']
print(acc)
print(death)
print(inj)
 
# acc = sum(data[0]["발생건수"])
# death = sum(data[0]["사망자수"])
# inj= sum(data[0]["부상자수"]) 

#2.    
acc_monthly = 0
death_monthly = 0
inj_monthly = 0
count =0
for j in range(0, 12): 
    count +=1
    for i in range(j, len(data), 12): 
        acc_monthly += data[i]['발생건수']
        death_monthly += data[i]['사망자수']
        inj_monthly += data[i]['부상자수']
        month = i%12 +1
    print("%d월 평균 사고 발생건수는 %d건, 사망자 수는 %d명, 부상자 수는 %d명 입니다." % (count, acc_monthly/len(data)*12, death_monthly/len(data)*12, inj_monthly/len(data)*12))

['\ufeff년도,월,발생건수,사망자수,부상자수\n', '2005,1,15494 ,504 ,25413 \n', '2005,2,13244 ,431 ,21635 \n', '2005,3,16580 ,477 ,25550 \n', '2005,4,17817 ,507 ,28131 \n', '2005,5,19085 ,571 ,29808 \n', '2005,6,18092 ,476 ,28594 \n', '2005,7,18675 ,528 ,29984 \n', '2005,8,19035 ,562 ,31603 \n', '2005,9,18759 ,577 ,29831 \n', '2005,10,19757 ,639 ,31597 \n', '2005,11,19129 ,574 ,30337 \n', '2005,12,18504 ,530 ,29750 \n', '2006,1,14971 ,420 ,24533 \n', '2006,2,14270 ,373 ,22903 \n', '2006,3,16767 ,465 ,26013 \n', '2006,4,17948 ,469 ,28725 \n', '2006,5,19140 ,531 ,30279 \n', '2006,6,17435 ,455 ,27032 \n', '2006,7,18634 ,516 ,29978 \n', '2006,8,18794 ,585 ,30882 \n', '2006,9,19293 ,580 ,30186 \n', '2006,10,19100 ,651 ,30715 \n', '2006,11,19877 ,701 ,31270 \n', '2006,12,17516 ,581 ,27713 \n', '2007,1,14914 ,468 ,23975 \n', '2007,2,14696 ,446 ,23717 \n', '2007,3,18166 ,476 ,28811 \n', '2007,4,18055 ,460 ,28555 \n', '2007,5,19264 ,516 ,30532 \n', '2007,6,18310 ,538 ,28662 \n', '2007,7,18037 ,503 ,28676 \n', '2007,8,17982 ,512 ,29711 \n', '2007,9,18506 ,532 ,29583 \n', '2007,10,19026 ,582 ,29802 \n', '2007,11,17815 ,565 ,27674 \n', '2007,12,16891 ,568 ,26208 \n', '2008,1,14741 ,444 ,23522 \n', '2008,2,14176 ,428 ,23282 \n', '2008,3,16752 ,502 ,26284 \n', '2008,4,17498 ,476 ,27364 \n', '2008,5,19515 ,493 ,30935 \n', '2008,6,18824 ,423 ,28872 \n', '2008,7,19562 ,452 ,30553 \n', '2008,8,18545 ,529 ,29705 \n', '2008,9,18023 ,502 ,27894 \n', '2008,10,19926 ,574 ,30882 \n', '2008,11,19597 ,528 ,30585 \n', '2008,12,18663 ,519 ,29084 \n', '2009,1,16532 ,475 ,27373 \n', '2009,2,15502 ,405 ,24429 \n', '2009,3,18224 ,468 ,27967 \n', '2009,4,19153 ,439 ,29521 \n', '2009,5,20237 ,519 ,31743 \n', '2009,6,19249 ,433 ,29084 \n', '2009,7,20281 ,454 ,31545 \n', '2009,8,19993 ,514 ,32200 \n', '2009,9,21004 ,500 ,31700 \n', '2009,10,21440 ,592 ,33255 \n', '2009,11,20156 ,522 ,31062 \n', '2009,12,20219 ,517 ,31996 \n', '2010,1,17124 ,438 ,27655 \n', '2010,2,15803 ,406 ,24968 \n', '2010,3,17801 ,396 ,27350 \n', '2010,4,18386 ,395 ,28191 \n', '2010,5,20372 ,447 ,31521 \n', '2010,6,18910 ,474 ,28311 \n', '2010,7,18965 ,453 ,29577 \n', '2010,8,19383 ,410 ,31032 \n', '2010,9,19439 ,436 ,30470 \n', '2010,10,21575 ,619 ,33282 \n', '2010,11,20271 ,541 ,30907 \n', '2010,12,18849 ,490 ,29194 \n', '2011,1,16454 ,395 ,25611 \n', '2011,2,14208 ,339 ,22493 \n', '2011,3,16832 ,338 ,25371 \n', '2011,4,18570 ,429 ,28534 \n', '2011,5,19414 ,393 ,29906 \n', '2011,6,18505 ,415 ,28469 \n', '2011,7,19253 ,462 ,29576 \n', '2011,8,18896 ,472 ,30034 \n', '2011,9,19065 ,474 ,29055 \n', '2011,10,20952 ,520 ,32133 \n', '2011,11,20283 ,514 ,30917 \n', '2011,12,19279 ,478 ,29292 \n', '2012,1,16818 ,418 ,26281 \n', '2012,2,16656 ,393 ,25998 \n', '2012,3,18255 ,403 ,27899 \n', '2012,4,19372 ,483 ,29628 \n', '2012,5,19672 ,444 ,30163 \n', '2012,6,18854 ,476 ,28314 \n', '2012,7,19333 ,416 ,29642 \n', '2012,8,18407 ,409 ,29051 \n', '2012,9,19234 ,486 ,29462 \n', '2012,10,19557 ,533 ,29759 \n', '2012,11,19750 ,508 ,30054 \n', '2012,12,17748 ,423 ,28314 \n', '2013,1,16016 ,389 ,25094 \n', '2013,2,14187 ,335 ,22255 \n', '2013,3,17465 ,409 ,26461 \n', '2013,4,18031 ,380 ,27795 \n', '2013,5,19686 ,420 ,29676 \n', '2013,6,18329 ,436 ,27673 \n', '2013,7,18441 ,444 ,28387 \n', '2013,8,18691 ,412 ,29190 \n', '2013,9,17806 ,430 ,26938 \n', '2013,10,19797 ,499 ,29507 \n', '2013,11,19396 ,479 ,28986 \n', '2013,12,17509 ,459 ,26749 \n', '2014,1,15905 ,389 ,24328 \n', '2014,2,14061 ,325 ,21501 \n', '2014,3,18420 ,358 ,27714 \n', '2014,4,18443 ,341 ,27323 \n', '2014,5,20314 ,398 ,30684 \n', '2014,6,18530 ,367 ,27740 \n', '2014,7,19649 ,407 ,29596 \n', '2014,8,19603 ,359 ,30633 \n', '2014,9,19243 ,445 ,29052 \n', '2014,10,20760 ,470 ,31199 \n', '2014,11,19872 ,476 ,29525 \n', '2014,12,18752 ,427 ,28202 \n', '2015,1,16902 ,381 ,25887 \n', '2015,2,14939 ,296 ,22999 \n', '2015,3,18616 ,378 ,27921 \n', '2015,4,19386 ,354 ,29431 \n', '2015,5,20543 ,389 ,31264 \n', '2015,6,18649 ,390 ,27469 \n', '2015,7,20278 ,359 ,30409 \n', '2015,8,19864 ,405 ,30618 \n', '2015,9,20811 ,387 ,31256 \n', '2015,10,21587 ,470 ,32436 \n', '2015,11,21170 ,410 ,31773 \n', '2015,12,19290 ,402 ,28937 \n', '2016,1,17067 ,336 ,26323 \n', '2016,2,15664 ,292 ,24021 \n', '2016,3,17946 ,310 ,26609 \n', '2016,4,19452 ,353 ,29216 \n', '2016,5,19554 ,347 ,29172 \n', '2016,6,17977 ,321 ,26668 \n', '2016,7,18955 ,358 ,28586 \n', '2016,8,18398 ,336 ,28017 \n', '2016,9,17883 ,375 ,26761 \n', '2016,10,19918 ,440 ,29635 \n', '2016,11,19234 ,416 ,28520 \n', '2016,12,18869 ,408 ,28192 \n', '2017,1,16970 ,353 ,26099 \n', '2017,2,14832 ,280 ,22323 \n', '2017,3,17047 ,295 ,25046 \n', '2017,4,17717 ,293 ,26530 \n', '2017,5,18502 ,366 ,27268 \n', '2017,6,18047 ,315 ,26454 \n', '2017,7,18158 ,357 ,27362 \n', '2017,8,18682 ,353 ,28162 \n', '2017,9,19891 ,419 ,29371 \n', '2017,10,18863 ,420 ,28698 \n', '2017,11,19377 ,379 ,28472 \n', '2017,12,18249 ,355 ,27044 \n', '2018,1,17026 ,304 ,25438 \n', '2018,2,16208 ,275 ,24630 \n', '2018,3,17022 ,310 ,25015 \n', '2018,4,17992 ,303 ,26643 \n', '2018,5,18636 ,309 ,27834 \n', '2018,6,18082 ,266 ,26574 \n', '2018,7,18699 ,315 ,28104 \n', '2018,8,18335 ,357 ,27749 \n', '2018,9,18371 ,348 ,27751 \n', '2018,10,19738 ,373 ,28836 \n', '2018,11,19029 ,298 ,28000 \n', '2018,12,18010 ,323 ,26463 ']
3084976
73436
4751813
1월 평균 사고 발생건수는 16209건, 사망자 수는 408명, 부상자 수는 25538명 입니다.
2월 평균 사고 발생건수는 31098건, 사망자 수는 767명, 부상자 수는 48906명 입니다.
3월 평균 사고 발생건수는 48662건, 사망자 수는 1165명, 부상자 수는 75621명 입니다.
4월 평균 사고 발생건수는 67078건, 사망자 수는 1571명, 부상자 수는 103877명 입니다.
5월 평균 사고 발생건수는 86644건, 사망자 수는 2010명, 부상자 수는 133933명 입니다.
6월 평균 사고 발생건수는 105058건, 사망자 수는 2423명, 부상자 수는 161784명 입니다.
7월 평균 사고 발생건수는 124124건, 사망자 수는 2854명, 부상자 수는 191211명 입니다.
8월 평균 사고 발생건수는 143024건, 사망자 수는 3298명, 부상자 수는 221110명 입니다.
9월 평균 사고 발생건수는 162119건, 사망자 수는 3761명, 부상자 수는 250346명 입니다.
10월 평균 사고 발생건수는 182262건, 사망자 수는 4288명, 부상자 수는 281185명 입니다.
11월 평균 사고 발생건수는 201902건, 사망자 수는 4782명, 부상자 수는 311048명 입니다.
12월 평균 사고 발생건수는 220355건, 사망자 수는 5245명, 부상자 수는 339415명 입니다.

In [91]:
# 풀이
# 추출한 데이터로 총 합 구하기

발생건수_합계 = 0
사망자수_합계 = 0
부상자수_합계 = 0

for item in data:
    발생건수_합계 += item['발생건수']
    사망자수_합계 += item['사망자수']
    부상자수_합계 += item['부상자수']

print("발생건수_합게: %d건" % 발생건수_합계)
print("사망자수_합게: %d건" % 사망자수_합계)
print("부상자수_합게: %d건" % 부상자수_합계)

# 2번 풀이
### case 1 - 결과값을 리스트에 저장하는 경우
발생건수_합계 = [0]*12 #[0,0,0,0,0,0,0,0,0,0,0,0]
발생건수_평균 = [0]*12
발생건수 = [0]*12

for item in data:
    # item -> {'년도': 2005, '월':1, '발생건수': 15494, '사망자수':504, '부상자수':25413
    monthIndex = item['월']-1
    발생건수_합계[monthIndex] += item['발생건수']
    발생건수[monthIndex] += 1
for i, v in enumerate(발생건수_합계):
    발생건수_평균[i] = v /발생건수[i]

print("발생건수_평균: %s\n" % 발생건수_평균)

발생건수_합게: 3084976건
사망자수_합게: 73436건
부상자수_합게: 4751813건
발생건수_평균: [16209.57142857143, 14889.0, 17563.785714285714, 18415.714285714286, 19566.714285714286, 18413.785714285714, 19065.714285714286, 18900.571428571428, 19094.85714285714, 20142.571428571428, 19639.714285714286, 18453.428571428572]

# 2) 해당 기간 동안의 교통사고의 발생건수, 사망자 수 , 부상자 수의 월 평균 값

monthly_acc =None
monthly_death = None
monthly_inj = None
monthly_counts = 0
for item in data:
    month_key = item['월']
    monthly_acc[month_key] += item['발생건수']
    monthly_death[month_key] += item['사망자수']
    monthly_inj[month_key] += item['부상자수']
    monthly_counts += 1

for month_key in monthly_acc:
    total_acc = monthly_acc[month_key]
    count = monthly_counts[month_key]
    if count>0:
        average = total_acc / count 
    else:
        average = 0

print(monthly_acc.items)